### PR TITLE
Fix logout button to user delete method.

### PR DESCRIPTION
**Pull request by pedro-saraiva88**

### CODE REVIEW

**Comment by niczero** [comment]
Do you have any info on why 'delete' should be considered better than 'post' here?

**Comment by pedro-saraiva88** [comment]
> Do you have any info on why 'delete' should be considered better than 'post' here?

Hi niczero.

I am proposing this change because of the delete method on the route file.

Route::delete('logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');

**Comment by niczero** [comment]
The change looks sensible and agrees with the Vue design.
It highlights the lack of tests.

**Comment by tranKILL** [comment]
Work for me, thanks ;)
Hope it will be publish

**Pull request closed without merging**
